# Generated by Django 5.1.6 on 2025-04-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepost',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
