# Generated by Django 5.1.6 on 2025-04-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ridepost_available_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('trip_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'trip_history',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
